### PR TITLE
Clean Mapnik output and errors

### PR DESCRIPTION
**Pull request by zstadler**
- Remove "is deprecated" error messages
- Redraw progress on the same line

### CODE REVIEW

**Comment by zstadler** [comment]
Now, while tile generation is active, the output looks like this:

```
$ docker-compose -f docker-compose.yml -f ./data/docker-compose-config.yml run --rm -u 197609:197121 generate-vectortiles
Generating tiles into /export/tiles.mbtiles for zooms 0..9 inside (25.1488889,22.0000374,36.8999418,34.6859694) using 10 threads
[24.434s]  34.3750%    143/   416 @    6/s | ✓ 142 □ 126 | 44s left
```

**Comment by TomPohys** [comment]
Hi @zstadler, thank you very much for this PR, it is awesome. 

I am thinking. if it is possible to change that by default it will print every record to a new line (old way but with nice time and without ```deprecated```) and if it needed the rewriting can be enabled? some ``QUITE=true`` flag? Which is already in [OMT Makefile](https://github.com/openmaptiles/openmaptiles/blob/master/Makefile#L13-L18)

What do you think?

**Comment by zstadler** [comment]
The goal of the PR is to align the UX with that of osm-import, avoiding the flooding of the screen with a new line for every generated tile.

This is also the intention of the [tilelive-copy](https://github.com/mapbox/tilelive/blob/0e8f6aaaec7944c9d1cb12496052aa1428721781/bin/tilelive-copy#L107) code:
```
process.stdout.write(util.format('\r\033[K[%s] %s%% %s/%s @ %s/s | ✓ %s □ %s | %s left',
```
Progress updates do not output a `\n`, which would have started new line. Instead, they start with a `\r` that returns the cursor to the beginning of the line, followed by a `\033[K` sequence that [erases everything to the end of the line](https://en.wikipedia.org/wiki/ANSI_escape_code#Terminal_output_sequences)

Capturing the output in a file, as done by Github Actions and `quickstart.sh`, provides access to all the progress details.

By the way, the decimal precision of the elapsed time was fixed in [tilelive@5.12.3](https://github.com/mapbox/tilelive/commit/389291a367bf46d3d9e9163ca7a9e03a00a4908c), released on Feb 3, 2017. Assuming OMT plans to continue to use `tilelive`, it would be useful to update to the latest version.

**Comment by nyurik** [comment]
This repository has been merged to [openmaptiles-tools](https://github.com/openmaptiles/openmaptiles-tools/tree/master/docker/generate-vectortiles), can you resubmit the change there? Thanks!

**Pull request closed without merging**
